Merging upstream version 4.4.
Signed-off-by: Daniel Baumann <daniel.baumann@progress-linux.org>

diff --git a/tests/25raid456-reshape-while-recovery b/tests/25raid456-reshape-while-recovery
--- a/tests/25raid456-reshape-while-recovery
+++ b/tests/25raid456-reshape-while-recovery
@@ -2,7 +2,7 @@ devs="$dev0 $dev1 $dev2"
 
 set_up_test()
 {
-	mdadm -Cv -R -n 3 -l5 $md0 $devs --assume-clean --size=50M || die "create array failed"
+	mdadm -Cv -R -n 3 -l5 $md0 $devs --assume-clean --size=10M || die "create array failed"
 	mdadm -a $md0 $dev3 $dev4 || die "failed to bind new disk to array"
 	echo 1000 > /sys/block/md0/md/sync_speed_max
 }
@@ -18,12 +18,12 @@ set_up_test || die "set up test failed"
 
 # set up replacement
 echo want_replacement > /sys/block/md0/md/rd0/state
-sleep 1
+sleep 2
 
 # trigger reshape
 echo frozen > /sys/block/md0/md/sync_action
 mdadm --grow -l 6 $md0
-sleep 1
+sleep 2
 
 # reassemeble array
 mdadm -S $md0 || die "can't stop array"
